### ISSUE TITLE
Error while creating system and database containers

### ISSUE THREAD

**Issue by oshando** [hobbit-project/java-sdk-example#5]
I'm trying to create docker containers for a system (runs a the system jar using the openjdk:8-jdk-alpine image) and a database that uses the mysql:5.5 image. Requests will then be sent from the SystemAdapter to the system containers for the tasks that are received. 

For the database container, I attempted to use the createContainer() method in the SystemAdapter init() method but I received an error. 

2018-04-11 23:18:06,803 ERROR [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Got exception while trying to request the creation of an instance of the "mysql:5.5" image.>
java.lang.NullPointerException: Didn't got a response for a create container message.
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.hobbit.core.components.AbstractCommandReceivingComponent.createContainer(AbstractCommandReceivingComponent.java:262)
	at org.hobbit.sdk.examples.examplebenchmark.system.SystemAdapter.init(SystemAdapter.java:34)
	at org.hobbit.sdk.ComponentsExecutor.lambda$submit$0(ComponentsExecutor.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

I also tried creating the container in the ExampleSystemTest class by using the PullBasedDockersBuilder but I got the following error:

2018-04-11 23:17:06,808 DEBUG [org.hobbit.sdk.utils.commandreactions.MultipleCommandsReaction] - <CONTAINER_START signal received with imageName=mysql:5.5>
2018-04-11 23:17:06,808 ERROR [org.hobbit.sdk.utils.CommandQueueListener] - <No component to start as imageName=mysql:5.5> 

I tried these methods based on what I saw in other repositories but I guess the implementation might be different when using the SDK. Can you point out what I might be doing wrong or provide any documentation that I can follow in order to create the containers?

**Comment by smirnp** [comment]
Hi! Are you running under sudo? I have checked the mysql image via PullBasedDockerizer and is starts normally:
```
2018-04-16 07:41:23,902 DEBUG [benchmark-controller-dockerizer] - <Creating container (imageName=mysql:5.5)>
2018-04-16 07:41:24,285 DEBUG [benchmark-controller-dockerizer] - <Starting container (imageName=mysql:5.5, containerId=8be9bed11933da85fc02ceecfa3a00d5fd9645311a9dd6ca6f2c2165c764cb6d)>
2018-04-16 07:41:24,767 DEBUG [benchmark-controller-dockerizer] - <Connecting container to networks (imageName=mysql:5.5)>
2018-04-16 07:41:25,403 DEBUG [benchmark-controller-dockerizer] - <Container started (imageName=mysql:5.5, containerId=8be9bed11933da85fc02ceecfa3a00d5fd9645311a9dd6ca6f2c2165c764cb6d)>
2018-04-16 07:41:25,403 DEBUG [benchmark-controller-dockerizer] - <Starting monitoring & logs reading for container (imageName=mysql:5.5)>
2018-04-16 07:41:25,519 ERROR [benchmark-controller-dockerizer] - <error: database is uninitialized and password option is not specified 
  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD 
```

**Comment by oshando** [comment]
I tried running both Docker and Intellij under sudo but it didn't make a difference. I still get the same error.

**Comment by smirnp** [comment]
Sorry for a long delay.
If the problem is still actual then can you confirm that other images (like rabbitmq) are starting correctly?
Otherwise it might be uncompatibility problem with installed docker (tested on versions 17, 18)

**Comment by oshando** [comment]
I'm still having the issue. Other containers are starting fine. The problem occurs when I use the createContainer() function in the SystemAdapter class. Even after defining the container image in ExampleSystemTest class, I still get the error in the error above:

[org.hobbit.core.components.AbstractCommandReceivingComponent] - <Got exception while trying to request the creation of an instance of the "mysql:5.5" image.>

**Comment by smirnp** [comment]
It might be a problem because the "mysql:5.5" was used as container ID, so it failed to create a container with such an id. Yesterday the bug was fixed.
